### ISSUE TITLE
[Missing File] No requirements file in repository

### ISSUE THREAD

**Issue by A135CF** [Twilight92z/Quantize-Watermark#1]
Dear author, 

I'm studying your paper and would like to reproduce your experiments. Unfortunately, when I configured the environment, I found that 

> Missing File: requirements.txt mentioned in the README did not exist

Could you please provide the relevant environment configuration file? Thank you very much!

**Comment by Twilight92z** [comment]
I am sorry for forgetting to upload the file requirements.txt which is now uploaded and includes some of the relevant python modules.
Hope this will solve your problem, and please contact me if you have any other questions!

**Comment by Twilight92z** [comment]
I am sorry for forgetting to upload the file requirements.txt which is now uploaded and includes some of the relevant python modules.
Hope this will solve your problem, and please contact me if you have any other questions!

**Comment by A135CF** [comment]
Thank you for your prompt reply!
